### ISSUE TITLE
Fatal error: Default value for parameters with a class type can only be NULL

### ISSUE THREAD

**Issue by syahnur197** [lavary/crunz#121]
require the package into a codeigniter project. I put the tasks folder in the application folder, cron manages to run the code in the tasks folder, but I got this error instead

**Comment by PabloKowalczyk** [comment]
Hello, could you paste exception stack trace and your configuration?

**Comment by PabloKowalczyk** [comment]
No response for 6 six months, I'm closing this issue. If you still have this problem please open new issue.

**Comment by SCSolutions** [comment]
Hi, i am getting the same issue after updating crunz here is the complete error message:

Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/vhosts/***/httpdocs/vendor/symfony/console/Application.php on line 85

How can i fix this?

**Comment by pwsebbi** [comment]
Hi, i am getting the same issue after updating crunz here is the complete error message:

Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/vhosts/***/httpdocs/vendor/symfony/console/Application.php on line 85

How can i fix this?

**Comment by PabloKowalczyk** [comment]
Hello @pwsebbi, could you open new issue and provide repository with code to reproduce?

**Comment by pwsebbi** [comment]
the issue was not with crunz, i found it. it was because on CLI level i was still running php5 which does not allow allow string as default values for typehints, hence produced the error above. Thanks

**Comment by SCSolutions** [comment]
Hi Sebbi,
wann haben wir einen RC für Partnerweb?

Bilal Stephens
Entrepreneur & Marketing Brain
+41(0)76 680 09 00





Swissconcept Solutions GmbH
Müllackerstrasse 10
8152 Opfikon
Switzerland
www.swissconcept.com




If you have received this email by mistake, please report this to us immediately. Reproduction or otherwise illegal use is not permitted.

 please don't print this e-mail unless it's necessary.
