### ISSUE TITLE
You really should credit code if you using someone elses

### ISSUE THREAD

**Issue by daveganley** [lavary/crunz#31]
https://github.com/lavary/crunz/blob/master/src/Event.php looks very much like a old version of Laravel Scheduling https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/Scheduling/Event.php

**Comment by lavary** [comment]
Hi Dave, maybe you need to read the code more deeply this time. `Event.php` has more 34 methods than Laravel's and most of the other methods are heavily refactored. And yes it's been inspired by Laravel Scheduler (because at first, it was dependent on Laravel's scheduling feature), which I've mentioned everywhere:

https://www.reddit.com/r/PHP/comments/4flwga/cron_manager_for_php_inspired_by_laravels_but/
https://www.sitepoint.com/framework-agnostic-php-cronjobs-made-easy-with-crunz/

Anyway thanks for the message.
You may read the Docs and the source code to see the difference.

**Comment by daveganley** [comment]
I didn't say you hadn't refactored or added. I could see the difference and knew where it had come from but NOT from within your code. Inspiration and parts of the original code used, should be credited in your code. Source code is god, linking to a couple of articles after being questioned about it doesn't really cut it. It's not like someone is going to google after reading your code to see if there is a article saying where it had come from

**Comment by lavary** [comment]
After been questioned?! I've introduced Crunz with those articles for the first time when no one knew it existed.

I can only add credit when someone else's logic is used, not when I use a few **method names with simple variable assignments in them**. I wish you read the code before trivializing other people's efforts.

**Comment by lavary** [comment]
I'll add the required information to the `Event.php` class.

**Comment by daveganley** [comment]
I never travilized your efforts as stated in your private message. I just said from the start put credit in your code. Its polite and gives other devs more information

**Comment by lavary** [comment]
Sorry to say this, but this issue tracker is for issues/enhancement/questions related to the code. Any other thing is better to be discussed through an email. You may also send a PR regarding the "more information" if you're concerned about that with above explanations.  I'll be pleased to merge.

Thanks.
